backend:
  name: github
  repo: AdrianGrs/AdrianGrsOfficialStore
  branch: main
  base_url: https://adrian-grs-official-store.vercel.app
  auth_endpoint: /api/auth

site_url: https://adrian-grs-official-store.vercel.app
display_url: https://adrian-grs-official-store.vercel.app

media_folder: "assets/uploads"
public_folder: "/assets/uploads"
media_library:
  name: uploadcare

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Image", name: "image", widget: "string" }
      - { label: "Small", name: "small", widget: "boolean", default: false }
