backend:
  name: github
  repo: AdrianGrs/AdrianGrsOfficialStore
  branch: main
  base_url: https://adrian-grs-official-store.vercel.app
  auth_endpoint: api/auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: products
    label: Produse
    folder: content/products
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - label: Titlu
        name: title
        widget: string
      - label: Descriere
        name: meta
        widget: string
        required: false
      - label: Categorie
        name: category
        widget: select
        options:
          - apple
          - gaming
          - accessories
          - shoes
          - beauty
          - watches
          - fashion
          - amazon
      - label: Tag
        name: tag
        widget: string
        required: false
      - label: Brand
        name: brand
        widget: string
        required: false
      - label: Link afiliat
        name: url
        widget: string
      - label: PozÄƒ
        name: image
        widget: image
      - label: Mic (small)
        name: small
        widget: boolean
        default: false
